In [1]:
import random
import string
import time
import tensorflow as tf
import numpy as np
from scipy import sparse

In [62]:
list_of_strs = [[string.ascii_lowercase[random.randrange(0, 26)] for i in range(random.randrange(2, 4))] for j in range(100)]

In [63]:
list_of_chars = set.union(*[set(i) for i in list_of_strs])

In [64]:
char_dict = {value:idx for idx, value in enumerate(sorted(list_of_chars))}

In [65]:
char_dict[' '] = max(char_dict.values())+1

In [66]:
max_length = max([len(i) for i in list_of_strs])

In [67]:
def onehot_string(x, max_length):
    
    if x!=x:
        return None
    
    #Pad to max length
    while len(x)<max_length:
        x+=' '
        
    sparse_matrix = sparse.hstack([sparse.csr_matrix([0 if char_dict[current_char]!=i else 1 for i in range(len(char_dict))]) for current_char in x])
    
    return sparse_matrix

In [68]:
n_tiles = 100

In [69]:
start_time = time.time()
sparse_strs = sparse.vstack([onehot_string(str_, max_length) for str_ in list_of_strs])
end_time = time.time()

In [70]:
dense_strs = sparse_strs.toarray()

In [71]:
dense_strs.shape

(100, 81)

In [72]:
vector_data = tf.placeholder(dtype=tf.float32, shape=dense_strs.shape)

In [73]:
tiled_vector_data = tf.reshape(tf.tile(vector_data, multiples=[1, n_tiles]), shape=[dense_strs.shape[0], n_tiles, dense_strs.shape[1]])

In [74]:
tile_test = tf.reshape(tf.tile(vector_data, multiples=[n_tiles, 1]), shape=[dense_strs.shape[0], n_tiles, dense_strs.shape[1]])

In [75]:
tf.transpose(tiled_vector_data, perm=[2, 1, 0])

<tf.Tensor 'transpose_4:0' shape=(81, 100, 100) dtype=float32>

In [76]:
#tiled_ref_vector_data = tf.reshape(tiled_vector_data, shape=[])

In [77]:
with tf.Session() as sess:
    t = sess.run([tiled_vector_data, tile_test], {vector_data:dense_strs})

In [78]:
t[1].shape

(100, 100, 81)

In [79]:
t[0].shape

(100, 100, 81)

In [80]:
t[1][0][:3]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.

In [82]:
t[0][0][:3]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.

In [20]:
t[-1][:,:513] == t[-1][:,513:513*2]

C:\Users\euix\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [67]:
t[-1][:,513:513*2]

array([[0., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)